<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var \Omeka\Form\ForgotPasswordForm $form
 */

$plugins = $this->getHelperPluginManager();
$escape = $plugins->get('escapeHtml');
$translate = $plugins->get('translate');
$pageTitle = $plugins->get('pageTitle');
$hyperlink = $plugins->get('hyperlink');
$htmlElement = $plugins->get('htmlElement');

$breadcrumbs = $plugins->has('breadcrumbs') ? $plugins->get('breadcrumbs') : null;

$htmlElement('body')->appendAttribute('class', 'guest guest-login forgot-password');
$form->prepare();
?>

<?php if ($breadcrumbs): ?>
    <?= $breadcrumbs() ?>
<?php else: ?>
<div class="breadcrumbs-parent">
    <nav id="breadcrumb" class="breadcrumbs" aria-label="<?= $translate('Breadcrumb') ?>">
        <ol>
            <li><?= $hyperlink($translate('Home'), $site->siteUrl()) ?></li>
            <li><span aria-current="page"><?= $escape('Forget password') ?></span></li>
        </ol>
    </nav>
</div>
<?php endif; ?>

<?= $pageTitle($translate('Forgot password')) ?>

<div class="block block-anonymous guest-anonymous guest-forgot-password">

    <?= $this->messages() ?>

    <?= $this->form()->openTag($form) ?>
        <?= $this->formCollection($form, false) ?>
        <button type="submit" class="button"><?= $translate('Send an email to reset the password') ?></button>
    <?= $this->form()->closeTag() ?>

</div>
