<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var \Omeka\Form\LoginForm|null $form
 * @var \Omeka\Form\UserForm|null $formRegister
 * @var \TwoFactorAuth\Form\TokenForm $formToken
 * @var string $htmlBeforeLogin
 * @var string $htmlAfterLogin
 * @var string $htmlBeforeRegister
 * @var string $htmlAfterRegister
 */

$plugins = $this->getHelperPluginManager();
$url = $plugins->get('url');
$trigger = $plugins->get('trigger');
$setting = $plugins->get('setting');
$escape = $plugins->get('escapeHtml');
$assetUrl = $plugins->get('assetUrl');
$translate = $plugins->get('translate');
$hyperlink = $plugins->get('hyperlink');
$pageTitle = $plugins->get('pageTitle');
$headLink = $plugins->get('headLink');
$siteSetting = $plugins->get('siteSetting');
$headScript = $plugins->get('headScript');
$htmlElement = $plugins->get('htmlElement');

$breadcrumbs = $plugins->has('breadcrumbs') ? $plugins->get('breadcrumbs') : null;

$htmlElement('body')->appendAttribute('class', 'guest login' . ($formToken ? ' two-factor-auth-login' : ''));

if ($form) $form->prepare();
if ($formRegister) $formRegister->prepare();

if ($formToken) {
    $headLink
        ->appendStylesheet($assetUrl('css/two-factor-auth.css', 'TwoFactorAuth'));
    $headScript
        ->appendFile($assetUrl('js/two-factor-auth.js', 'TwoFactorAuth'), 'text/javascript', ['defer' => 'defer']);
}

$pageLabel = $siteSetting('guest_login_text') ?: ($setting('guest_login_text') ?: $translate('Log in'));
?>

<?php if ($breadcrumbs): ?>
    <?= $breadcrumbs() ?>
<?php else: ?>
<div class="breadcrumbs-parent">
    <nav id="breadcrumb" class="breadcrumbs" aria-label="<?= $translate('Breadcrumb') ?>">
        <ol>
            <li><?= $hyperlink($translate('Home'), $site->siteUrl()) ?></li>
            <li><span aria-current="page"><?= $escape($pageLabel) ?></span></li>
        </ol>
    </nav>
</div>
<?php endif; ?>

<?= $pageTitle($pageLabel) ?>

<div class="block block-group guest-anonymous">

<?php if ($htmlBeforeLogin): ?>
<div class="block block-html guest-anonymous">
    <?= $htmlBeforeLogin ?>
</div>
<?php endif; ?>

<div class="block block-login guest-anonymous guest-login">

    <?= $this->messages() ?>

    <?php if ($form): ?>
    <?= $this->form($form) ?>
    <p class="forgot-password">
        <?= $hyperlink($translate('Forgot password?'), $url('site/guest/anonymous', ['action' => 'forgot-password'], true)) ?>
    </p>
    <?= isset($formToken) ? $this->partial('common/dialog/2fa-token', ['site' => $site, 'form' => $formToken]) : '' ?>
    <?php endif; ?>

    <?php $trigger('view.login.after'); ?>

</div>

<?php if ($htmlAfterLogin): ?>
<div class="block block-html guest-anonymous">
    <?= $htmlAfterLogin ?>
</div>
<?php endif; ?>

<?php if ($formRegister): ?>

<?php if ($htmlBeforeRegister): ?>
<div class="block block-html guest-anonymous">
    <?= $htmlBeforeRegister ?>
</div>
<?php endif; ?>

<div class="block-register guest-anonymous guest-register">

    <?= $this->messages() ?>

    <div>
        <?= $siteSetting('guest_capabilities') ?: $setting('guest_capabilities') ?>
    </div>

    <?= $this->form()->openTag($formRegister) ?>
        <?= $this->formCollection($formRegister, false) ?>
        <?php $trigger('view.add.form.after'); ?>
        <div id="page-actions">
            <button type="submit" class="button"><?= $translate('Register') ?></button>
        </div>
    <?= $this->form()->closeTag() ?>

    <?php $trigger('view.add.after'); ?>

</div>

<?php if ($htmlAfterRegister): ?>
<div class="block block-html guest-anonymous">
    <?= $htmlAfterRegister ?>
</div>
<?php endif; ?>

<?php endif; ?>

</div>
