<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var \Omeka\Api\Representation\SitePageBlockRepresentation $block
 * @var \TwoFactorAuth\Form\TokenForm $formToken
 */

$plugins = $this->getHelperPluginManager();
$translate = $plugins->get('translate');
$hyperlink = $plugins->get('hyperlink');
?>

<div class="block block-login">

    <?= $this->messages() ?>

    <div  class="guest-anonymous guest-login guest-login-token two-factor-auth-login">
        <?= $this->form($formToken) ?>

        <p class="resend-token">
            <?= $hyperlink($translate('Resend a code'), $block->page()->siteUrl() . '?resend_token=1', ['class' => 'resend-code']) ?>
        </p>
    </div>

</div>
