<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var \Omeka\Api\Representation\SitePageBlockRepresentation $block
 * @var \Guest\Form\UserForm $form
 */

$plugins = $this->getHelperPluginManager();
$trigger = $plugins->get('trigger');
$setting = $plugins->get('setting');
$translate = $plugins->get('translate');
$siteSetting = $plugins->get('siteSetting');

$form->prepare();
?>

<div class="block block-register">

    <?= $this->messages() ?>

    <div class="guest-anonymous guest-register">
        <div>
            <?= $siteSetting('guest_capabilities') ?: $setting('guest_capabilities') ?>
        </div>
        <?= $this->form()->openTag($form) ?>
            <?= $this->formCollection($form, false) ?>
            <?php $trigger('view.add.form.after'); ?>
            <div id="page-actions">
                <button type="submit" class="button"><?= $translate('Register') ?></button>
            </div>
        <?= $this->form()->closeTag() ?>
        <?php $trigger('view.add.after'); ?>
    </div>

</div>
