<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var \Omeka\Api\Representation\SitePageBlockRepresentation $block
 * @var \Omeka\Form\ForgotPasswordForm $form
 */

$plugins = $this->getHelperPluginManager();
$trigger = $plugins->get('trigger');
$translate = $plugins->get('translate');

$form->prepare();
?>

<div class="block block-forgot-password">

    <?= $this->messages() ?>

    <div class="guest-anonymous guest-forgot-password">
        <?= $this->form()->openTag($form) ?>
            <?= $this->formCollection($form, false) ?>
            <?php $trigger('view.add.form.after'); ?>
            <div id="page-actions">
                <button type="submit" class="button"><?= $translate('Submit') ?></button>
            </div>
        <?= $this->form()->closeTag() ?>
        <?php $trigger('view.add.after'); ?>
    </div>

</div>
