<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var \Omeka\Api\Representation\SitePageBlockRepresentation $block
 * @var \Omeka\Form\LoginForm|null $form
 * @var \TwoFactorAuth\Form\TokenForm|null $formToken
 */

$plugins = $this->getHelperPluginManager();
$url = $plugins->get('url');
$trigger = $plugins->get('trigger');
$assetUrl = $plugins->get('assetUrl');
$translate = $plugins->get('translate');
$hyperlink = $plugins->get('hyperlink');
$headLink = $plugins->get('headLink');
$headScript = $plugins->get('headScript');

if ($form) $form->prepare();

if (!empty($formToken)) {
    $headLink
        ->appendStylesheet($assetUrl('css/two-factor-auth.css', 'TwoFactorAuth'));
    $headScript
        ->appendFile($assetUrl('js/two-factor-auth.js', 'TwoFactorAuth'), 'text/javascript', ['defer' => 'defer']);
}
?>

<div class="block block-login">

    <?= $this->messages() ?>

    <?php if ($form): ?>
    <div  class="guest-anonymous guest-login">
        <?= $this->form($form) ?>
    </div>
    <p class="forgot-password">
        <?= $hyperlink($translate('Forgot password?'), $url('site/guest/anonymous', ['action' => 'forgot-password'], true)) ?>
    </p>
    <?= isset($formToken) ? $this->partial('common/dialog/2fa-token', ['site' => $site, 'form' => $formToken]) : '' ?>
    <?php endif; ?>

    <?php $trigger('view.login.after'); // Needed as long as other auth modules have no block. ?>

</div>
