<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var \Omeka\Entity\User $user
 * @var \Guest\Form\EmailForm $form
 */

$plugins = $this->getHelperPluginManager();
$translate = $plugins->get('translate');
$pageTitle = $plugins->get('pageTitle');
$breadcrumbs = $plugins->has('breadcrumbs') ? $plugins->get('breadcrumbs') : null;
$guestNavigation = $plugins->get('guestNavigation')();

$hasGuestNav = (bool) $guestNavigation->getContainer()->count();

$this->htmlElement('body')->appendAttribute('class', 'guest account');

$form->prepare();
?>

<?php if ($breadcrumbs && !$hasGuestNav): ?>
<?= $breadcrumbs() ?>
<?php endif; ?>

<?php if ($hasGuestNav): ?>
<nav class="navigation-guest">
    <?= $guestNavigation->menu()->renderMenu() ?>
</nav>
<?php endif; ?>

<?= $this->messages() ?>

<?= $pageTitle($translate('My email')) ?>

<?= $this->form()->openTag($form) ?>
<?= $this->formCollection($form, false) ?>
<?php $this->trigger('view.add.form.after'); ?>
<div id="page-actions">
    <button type="submit" class="button"><?= $translate('Update') ?></button>
</div>
<?= $this->form()->closeTag() ?>

<?php $this->trigger('view.add.after'); ?>
